package main

// The receipt is deliberately separate from connection settings. It contains
// paths and fingerprints, never credentials, configuration text or session data.
import (
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/user"
	"path/filepath"
	"runtime"
	"strings"
)

var toolNames = []string{"codex", "grok", "claude", "cursor", "opencode"}

type ownedNode struct {
	Kind string `json:"kind"`
	Hash string `json:"sha256,omitempty"`
	Link string `json:"link,omitempty"`
}
type ownedProgram struct {
	Entry string               `json:"entry"`
	Nodes map[string]ownedNode `json:"nodes"` // paths relative to the configuration root
}
type generatedFile struct {
	Hash   string            `json:"sha256"`
	Fields map[string]string `json:"fields,omitempty"`
}
type pathAddition struct {
	File      string `json:"file,omitempty"` // empty denotes Windows User PATH
	Directory string `json:"directory"`
	Block     string `json:"block,omitempty"` // only the literal PATH block generated by the installer
}
type installState struct {
	Schema         int                      `json:"schema_version"`
	Root           string                   `json:"root"`
	User           string                   `json:"user"`
	Executable     string                   `json:"executable,omitempty"`
	ExecutableHash string                   `json:"executable_sha256,omitempty"`
	DirectoryOwned bool                     `json:"directory_owned,omitempty"`
	Profiles       map[string]bool          `json:"profiles,omitempty"`
	Programs       map[string]ownedProgram  `json:"programs,omitempty"`
	Generated      map[string]generatedFile `json:"generated,omitempty"`
	Path           []pathAddition           `json:"path,omitempty"`
	Pending        string                   `json:"pending,omitempty"`
}

func digest(b []byte) string { return fmt.Sprintf("%x", sha256.Sum256(b)) }

func pathDigest(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", h.Sum(nil)), nil
}

func readInstallState(root string) (installState, error) {
	if strings.TrimSpace(root) == "" {
		return installState{}, errors.New("未指定安装配置根目录")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return installState{}, err
	}
	u, err := user.Current()
	if err != nil {
		return installState{}, err
	}
	s := installState{Schema: 1, Root: abs, User: u.Uid, Profiles: map[string]bool{}, Programs: map[string]ownedProgram{}, Generated: map[string]generatedFile{}}
	path := filepath.Join(abs, "install-state.json")
	if err := noLinkPath(path); err != nil {
		return s, err
	}
	b, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return s, nil
	}
	if err != nil {
		return s, err
	}
	if len(b) > 32<<20 || json.Unmarshal(b, &s) != nil {
		return s, errors.New("安装归属记录损坏，拒绝推断删除范围")
	}
	if s.Schema != 1 || s.Root != abs || s.User != u.Uid {
		return s, errors.New("安装归属记录与当前目录或用户不匹配")
	}
	if s.Profiles == nil {
		s.Profiles = map[string]bool{}
	}
	if s.Programs == nil {
		s.Programs = map[string]ownedProgram{}
	}
	if s.Generated == nil {
		s.Generated = map[string]generatedFile{}
	}
	return s, nil
}

func (s *installState) save() error {
	b, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return err
	}
	return atomicWrite(filepath.Join(s.Root, "install-state.json"), append(b, '\n'), 0600)
}

// noLinkPath checks every existing component, including Windows reparse points.
// A missing leaf is allowed for retry; a linked parent never confers ownership.
func noLinkPath(path string) error {
	abs, err := filepath.Abs(path)
	if err != nil {
		return err
	}
	for p := abs; ; p = filepath.Dir(p) {
		st, err := os.Lstat(p)
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err == nil && (st.Mode()&os.ModeSymlink != 0 || isReparse(st)) {
			return fmt.Errorf("路径含符号链接或重解析点，拒绝清理：%s", p)
		}
		if filepath.Dir(p) == p {
			break
		}
	}
	return nil
}

func safeRelative(root, rel string) (string, error) {
	if rel == "." || !filepath.IsLocal(rel) {
		return "", errors.New("安装记录含越界路径")
	}
	return filepath.Join(root, rel), nil
}

func (a *app) programRoot(name, entry string) (string, error) {
	abs, err := filepath.Abs(entry)
	if err != nil {
		return "", err
	}
	root, _ := filepath.Abs(a.root)
	want := filepath.Join(root, "tools", name, "bin")
	if name == "cursor" {
		want = filepath.Join(root, "tools", name, "app")
	}
	if name == "codex" {
		want = filepath.Dir(filepath.Dir(abs))
		parent := filepath.Join(codexStandaloneDir(root), "releases")
		target, err := codexVendorTarget(runtime.GOOS, runtime.GOARCH)
		if err != nil || filepath.Dir(want) != parent || codexReleaseVersion(filepath.Base(want), target) == "" || filepath.Base(filepath.Dir(abs)) != "bin" {
			return "", errors.New("Codex 程序不在受管 release 落点")
		}
	}
	if abs != filepath.Join(want, toolBinaryName(name)) && !(name == "codex" && abs == filepath.Join(want, "bin", toolBinaryName(name))) {
		return "", fmt.Errorf("%s 程序不在固定受管落点", name)
	}
	if err := noLinkPath(want); err != nil {
		return "", err
	}
	return want, nil
}

func snapshotTree(root, dir string) (map[string]ownedNode, error) {
	nodes := map[string]ownedNode{}
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil || !filepath.IsLocal(rel) {
			return errors.New("受管目录越界")
		}
		n := ownedNode{Kind: "file"}
		switch {
		case d.Type()&os.ModeSymlink != 0:
			n.Kind = "link"
			n.Link, err = os.Readlink(path)
		case d.IsDir():
			st, e := d.Info()
			if e != nil {
				return e
			}
			if isReparse(st) {
				return errors.New("受管目录包含重解析点")
			}
			n.Kind = "dir"
		case d.Type().IsRegular():
			n.Hash, err = pathDigest(path)
		default:
			return fmt.Errorf("受管目录含不支持的文件类型：%s", path)
		}
		if err != nil {
			return err
		}
		nodes[rel] = n
		return nil
	})
	return nodes, err
}

func (a *app) recordProgram(name, entry string) error {
	s, err := readInstallState(a.root)
	if err != nil {
		return err
	}
	dir, err := a.programRoot(name, entry)
	if err != nil {
		return err
	}
	nodes, err := snapshotTree(s.Root, dir)
	if err != nil {
		return err
	}
	if name != "codex" && name != "cursor" {
		for rel := range nodes {
			if filepath.Join(s.Root, rel) != dir && filepath.Join(s.Root, rel) != entry {
				delete(nodes, rel)
			}
		}
	}
	// Preserve inventory of other releases and unknown additions; an update owns
	// precisely its newly installed tree, not every file in tools/<name>.
	old := s.Programs[name]
	if old.Nodes == nil {
		old.Nodes = map[string]ownedNode{}
	}
	for rel, n := range nodes {
		old.Nodes[rel] = n
	}
	old.Entry, _ = filepath.Abs(entry)
	s.Programs[name] = old
	return s.save()
}

func generatedNames(name string) []string {
	switch name {
	case "codex":
		return []string{"config.toml", "model-catalog.json"}
	case "grok":
		return []string{"config.toml"}
	case "claude":
		return []string{"settings.json", "cli-settings.json"}
	case "cursor":
		return []string{"cli-config.json"}
	case "opencode":
		return []string{"opencode.json"}
	}
	return nil
}

func jsonFieldHashes(value any, prefix string, fields map[string]string) {
	if obj, ok := value.(map[string]any); ok && len(obj) > 0 {
		for k, v := range obj {
			jsonFieldHashes(v, prefix+"/"+strings.ReplaceAll(strings.ReplaceAll(k, "~", "~0"), "/", "~1"), fields)
		}
		return
	}
	b, _ := json.Marshal(value)
	fields[prefix] = digest(b)
}

func describeGenerated(name, file string, b []byte) generatedFile {
	r := generatedFile{Hash: digest(b), Fields: map[string]string{}}
	if strings.HasSuffix(file, ".json") && !strings.Contains(file, "catalog") {
		var obj map[string]any
		if json.Unmarshal(b, &obj) == nil {
			if name == "cursor" {
				obj = map[string]any{"network": map[string]any{"useHttp1ForAgent": true}}
			}
			jsonFieldHashes(obj, "", r.Fields)
		}
	} else if name == "codex" && file == "config.toml" {
		for _, key := range []string{"model", "model_provider", "model_catalog_json"} {
			if v, ok := tomlTopLevel(string(b), key); ok {
				r.Fields[key] = digest([]byte(v))
			}
		}
		start, end := tomlSectionBounds(string(b), sharedProviderHeader)
		if start >= 0 {
			r.Fields[sharedProviderHeader] = digest([]byte(strings.TrimSpace(string(b[start:end]))))
		}
	}
	return r
}

func (a *app) recordProfile(name string) error {
	s, err := readInstallState(a.root)
	if err != nil {
		return err
	}
	s.Profiles[name] = true
	return s.save()
}

func (a *app) recordGenerated(name string) error {
	s, err := readInstallState(a.root)
	if err != nil {
		return err
	}
	s.Profiles[name] = true
	for _, file := range generatedNames(name) {
		rel := filepath.Join("tools", name, "derived", file)
		b, err := os.ReadFile(filepath.Join(s.Root, rel))
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return err
		}
		s.Generated[rel] = describeGenerated(name, file, b)
	}
	return s.save()
}

func (a *app) recordExecutable(target string) error {
	s, err := readInstallState(a.root)
	if err != nil {
		return err
	}
	abs, err := filepath.Abs(target)
	if err != nil {
		return err
	}
	if err := noLinkPath(abs); err != nil {
		return err
	}
	hash, err := pathDigest(abs)
	if err != nil {
		return err
	}
	if s.Executable != abs {
		s.DirectoryOwned = false
	}
	s.Executable, s.ExecutableHash = abs, hash
	if err := s.save(); err != nil {
		return err
	}
	locator := installLocator{Schema: 1, Root: s.Root, User: s.User, Executable: abs}
	b, err := json.Marshal(locator)
	if err != nil {
		return err
	}
	return writeUserFile(abs+".install.json", append(b, '\n'), 0600)
}

// The small credential-free locator binds custom configuration roots to an
// executable. Changing GATE_CONFIG_DIR at uninstall time cannot select a new
// deletion root. The full receipt remains in the actual configuration root.
type installLocator struct {
	Schema     int    `json:"schema_version"`
	Root       string `json:"root"`
	User       string `json:"user"`
	Executable string `json:"executable"`
}

func uninstallRootForExecutable(fallback, target string) (string, error) {
	if err := noLinkPath(target + ".install.json"); err != nil {
		return "", err
	}
	b, err := os.ReadFile(target + ".install.json")
	if errors.Is(err, os.ErrNotExist) {
		return fallback, nil
	}
	if err != nil {
		return "", err
	}
	var locator installLocator
	u, err := user.Current()
	if err != nil {
		return "", err
	}
	if len(b) > 64<<10 || json.Unmarshal(b, &locator) != nil || locator.Schema != 1 || locator.User != u.Uid || locator.Executable != target || !filepath.IsAbs(locator.Root) {
		return "", errors.New("gate 安装定位记录无效，拒绝推断清理目录")
	}
	s, err := readInstallState(locator.Root)
	if err != nil {
		return "", err
	}
	if s.Executable != "" && s.Executable != target {
		return "", errors.New("gate 安装定位与归属记录不匹配")
	}
	return locator.Root, nil
}
